// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgReadProto.proto

package com.bx.im.proto;

public final class MsgReadProto {
  private MsgReadProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgReadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:im.MsgRead)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *uid用户确认了toId的消息，即toId发给uid的消息已读
     * </pre>
     *
     * <code>int64 uid = 1;</code>
     * @return The uid.
     */
    long getUid();

    /**
     * <code>int64 toId = 2;</code>
     * @return The toId.
     */
    long getToId();

    /**
     * <pre>
     * 根据msgid即可操作数据库（唯一）
     * </pre>
     *
     * <code>repeated string msgIds = 3;</code>
     * @return A list containing the msgIds.
     */
    java.util.List<java.lang.String>
        getMsgIdsList();
    /**
     * <pre>
     * 根据msgid即可操作数据库（唯一）
     * </pre>
     *
     * <code>repeated string msgIds = 3;</code>
     * @return The count of msgIds.
     */
    int getMsgIdsCount();
    /**
     * <pre>
     * 根据msgid即可操作数据库（唯一）
     * </pre>
     *
     * <code>repeated string msgIds = 3;</code>
     * @param index The index of the element to return.
     * @return The msgIds at the given index.
     */
    java.lang.String getMsgIds(int index);
    /**
     * <pre>
     * 根据msgid即可操作数据库（唯一）
     * </pre>
     *
     * <code>repeated string msgIds = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the msgIds at the given index.
     */
    com.google.protobuf.ByteString
        getMsgIdsBytes(int index);

    /**
     * <pre>
     * 留待群聊已读功能，用以区分单聊群聊
     * </pre>
     *
     * <code>int32 type = 4;</code>
     * @return The type.
     */
    int getType();
  }
  /**
   * Protobuf type {@code im.MsgRead}
   */
  public static final class MsgRead extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:im.MsgRead)
      MsgReadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgRead.newBuilder() to construct.
    private MsgRead(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgRead() {
      msgIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MsgRead();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgRead(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              uid_ = input.readInt64();
              break;
            }
            case 16: {

              toId_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                msgIds_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              msgIds_.add(s);
              break;
            }
            case 32: {

              type_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          msgIds_ = msgIds_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bx.im.proto.MsgReadProto.internal_static_im_MsgRead_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bx.im.proto.MsgReadProto.internal_static_im_MsgRead_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bx.im.proto.MsgReadProto.MsgRead.class, com.bx.im.proto.MsgReadProto.MsgRead.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private long uid_;
    /**
     * <pre>
     *uid用户确认了toId的消息，即toId发给uid的消息已读
     * </pre>
     *
     * <code>int64 uid = 1;</code>
     * @return The uid.
     */
    @java.lang.Override
    public long getUid() {
      return uid_;
    }

    public static final int TOID_FIELD_NUMBER = 2;
    private long toId_;
    /**
     * <code>int64 toId = 2;</code>
     * @return The toId.
     */
    @java.lang.Override
    public long getToId() {
      return toId_;
    }

    public static final int MSGIDS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList msgIds_;
    /**
     * <pre>
     * 根据msgid即可操作数据库（唯一）
     * </pre>
     *
     * <code>repeated string msgIds = 3;</code>
     * @return A list containing the msgIds.
     */
    public com.google.protobuf.ProtocolStringList
        getMsgIdsList() {
      return msgIds_;
    }
    /**
     * <pre>
     * 根据msgid即可操作数据库（唯一）
     * </pre>
     *
     * <code>repeated string msgIds = 3;</code>
     * @return The count of msgIds.
     */
    public int getMsgIdsCount() {
      return msgIds_.size();
    }
    /**
     * <pre>
     * 根据msgid即可操作数据库（唯一）
     * </pre>
     *
     * <code>repeated string msgIds = 3;</code>
     * @param index The index of the element to return.
     * @return The msgIds at the given index.
     */
    public java.lang.String getMsgIds(int index) {
      return msgIds_.get(index);
    }
    /**
     * <pre>
     * 根据msgid即可操作数据库（唯一）
     * </pre>
     *
     * <code>repeated string msgIds = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the msgIds at the given index.
     */
    public com.google.protobuf.ByteString
        getMsgIdsBytes(int index) {
      return msgIds_.getByteString(index);
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <pre>
     * 留待群聊已读功能，用以区分单聊群聊
     * </pre>
     *
     * <code>int32 type = 4;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (uid_ != 0L) {
        output.writeInt64(1, uid_);
      }
      if (toId_ != 0L) {
        output.writeInt64(2, toId_);
      }
      for (int i = 0; i < msgIds_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, msgIds_.getRaw(i));
      }
      if (type_ != 0) {
        output.writeInt32(4, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (uid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, uid_);
      }
      if (toId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, toId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < msgIds_.size(); i++) {
          dataSize += computeStringSizeNoTag(msgIds_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getMsgIdsList().size();
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bx.im.proto.MsgReadProto.MsgRead)) {
        return super.equals(obj);
      }
      com.bx.im.proto.MsgReadProto.MsgRead other = (com.bx.im.proto.MsgReadProto.MsgRead) obj;

      if (getUid()
          != other.getUid()) return false;
      if (getToId()
          != other.getToId()) return false;
      if (!getMsgIdsList()
          .equals(other.getMsgIdsList())) return false;
      if (getType()
          != other.getType()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUid());
      hash = (37 * hash) + TOID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getToId());
      if (getMsgIdsCount() > 0) {
        hash = (37 * hash) + MSGIDS_FIELD_NUMBER;
        hash = (53 * hash) + getMsgIdsList().hashCode();
      }
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bx.im.proto.MsgReadProto.MsgRead parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bx.im.proto.MsgReadProto.MsgRead parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bx.im.proto.MsgReadProto.MsgRead parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bx.im.proto.MsgReadProto.MsgRead parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bx.im.proto.MsgReadProto.MsgRead parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bx.im.proto.MsgReadProto.MsgRead parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bx.im.proto.MsgReadProto.MsgRead parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bx.im.proto.MsgReadProto.MsgRead parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bx.im.proto.MsgReadProto.MsgRead parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bx.im.proto.MsgReadProto.MsgRead parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bx.im.proto.MsgReadProto.MsgRead parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bx.im.proto.MsgReadProto.MsgRead parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bx.im.proto.MsgReadProto.MsgRead prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code im.MsgRead}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:im.MsgRead)
        com.bx.im.proto.MsgReadProto.MsgReadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bx.im.proto.MsgReadProto.internal_static_im_MsgRead_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bx.im.proto.MsgReadProto.internal_static_im_MsgRead_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bx.im.proto.MsgReadProto.MsgRead.class, com.bx.im.proto.MsgReadProto.MsgRead.Builder.class);
      }

      // Construct using com.bx.im.proto.MsgReadProto.MsgRead.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uid_ = 0L;

        toId_ = 0L;

        msgIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bx.im.proto.MsgReadProto.internal_static_im_MsgRead_descriptor;
      }

      @java.lang.Override
      public com.bx.im.proto.MsgReadProto.MsgRead getDefaultInstanceForType() {
        return com.bx.im.proto.MsgReadProto.MsgRead.getDefaultInstance();
      }

      @java.lang.Override
      public com.bx.im.proto.MsgReadProto.MsgRead build() {
        com.bx.im.proto.MsgReadProto.MsgRead result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bx.im.proto.MsgReadProto.MsgRead buildPartial() {
        com.bx.im.proto.MsgReadProto.MsgRead result = new com.bx.im.proto.MsgReadProto.MsgRead(this);
        int from_bitField0_ = bitField0_;
        result.uid_ = uid_;
        result.toId_ = toId_;
        if (((bitField0_ & 0x00000001) != 0)) {
          msgIds_ = msgIds_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.msgIds_ = msgIds_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bx.im.proto.MsgReadProto.MsgRead) {
          return mergeFrom((com.bx.im.proto.MsgReadProto.MsgRead)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bx.im.proto.MsgReadProto.MsgRead other) {
        if (other == com.bx.im.proto.MsgReadProto.MsgRead.getDefaultInstance()) return this;
        if (other.getUid() != 0L) {
          setUid(other.getUid());
        }
        if (other.getToId() != 0L) {
          setToId(other.getToId());
        }
        if (!other.msgIds_.isEmpty()) {
          if (msgIds_.isEmpty()) {
            msgIds_ = other.msgIds_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMsgIdsIsMutable();
            msgIds_.addAll(other.msgIds_);
          }
          onChanged();
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bx.im.proto.MsgReadProto.MsgRead parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bx.im.proto.MsgReadProto.MsgRead) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long uid_ ;
      /**
       * <pre>
       *uid用户确认了toId的消息，即toId发给uid的消息已读
       * </pre>
       *
       * <code>int64 uid = 1;</code>
       * @return The uid.
       */
      @java.lang.Override
      public long getUid() {
        return uid_;
      }
      /**
       * <pre>
       *uid用户确认了toId的消息，即toId发给uid的消息已读
       * </pre>
       *
       * <code>int64 uid = 1;</code>
       * @param value The uid to set.
       * @return This builder for chaining.
       */
      public Builder setUid(long value) {
        
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *uid用户确认了toId的消息，即toId发给uid的消息已读
       * </pre>
       *
       * <code>int64 uid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUid() {
        
        uid_ = 0L;
        onChanged();
        return this;
      }

      private long toId_ ;
      /**
       * <code>int64 toId = 2;</code>
       * @return The toId.
       */
      @java.lang.Override
      public long getToId() {
        return toId_;
      }
      /**
       * <code>int64 toId = 2;</code>
       * @param value The toId to set.
       * @return This builder for chaining.
       */
      public Builder setToId(long value) {
        
        toId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 toId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearToId() {
        
        toId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList msgIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMsgIdsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          msgIds_ = new com.google.protobuf.LazyStringArrayList(msgIds_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * 根据msgid即可操作数据库（唯一）
       * </pre>
       *
       * <code>repeated string msgIds = 3;</code>
       * @return A list containing the msgIds.
       */
      public com.google.protobuf.ProtocolStringList
          getMsgIdsList() {
        return msgIds_.getUnmodifiableView();
      }
      /**
       * <pre>
       * 根据msgid即可操作数据库（唯一）
       * </pre>
       *
       * <code>repeated string msgIds = 3;</code>
       * @return The count of msgIds.
       */
      public int getMsgIdsCount() {
        return msgIds_.size();
      }
      /**
       * <pre>
       * 根据msgid即可操作数据库（唯一）
       * </pre>
       *
       * <code>repeated string msgIds = 3;</code>
       * @param index The index of the element to return.
       * @return The msgIds at the given index.
       */
      public java.lang.String getMsgIds(int index) {
        return msgIds_.get(index);
      }
      /**
       * <pre>
       * 根据msgid即可操作数据库（唯一）
       * </pre>
       *
       * <code>repeated string msgIds = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the msgIds at the given index.
       */
      public com.google.protobuf.ByteString
          getMsgIdsBytes(int index) {
        return msgIds_.getByteString(index);
      }
      /**
       * <pre>
       * 根据msgid即可操作数据库（唯一）
       * </pre>
       *
       * <code>repeated string msgIds = 3;</code>
       * @param index The index to set the value at.
       * @param value The msgIds to set.
       * @return This builder for chaining.
       */
      public Builder setMsgIds(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMsgIdsIsMutable();
        msgIds_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 根据msgid即可操作数据库（唯一）
       * </pre>
       *
       * <code>repeated string msgIds = 3;</code>
       * @param value The msgIds to add.
       * @return This builder for chaining.
       */
      public Builder addMsgIds(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMsgIdsIsMutable();
        msgIds_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 根据msgid即可操作数据库（唯一）
       * </pre>
       *
       * <code>repeated string msgIds = 3;</code>
       * @param values The msgIds to add.
       * @return This builder for chaining.
       */
      public Builder addAllMsgIds(
          java.lang.Iterable<java.lang.String> values) {
        ensureMsgIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, msgIds_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 根据msgid即可操作数据库（唯一）
       * </pre>
       *
       * <code>repeated string msgIds = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgIds() {
        msgIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 根据msgid即可操作数据库（唯一）
       * </pre>
       *
       * <code>repeated string msgIds = 3;</code>
       * @param value The bytes of the msgIds to add.
       * @return This builder for chaining.
       */
      public Builder addMsgIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureMsgIdsIsMutable();
        msgIds_.add(value);
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       * 留待群聊已读功能，用以区分单聊群聊
       * </pre>
       *
       * <code>int32 type = 4;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       * 留待群聊已读功能，用以区分单聊群聊
       * </pre>
       *
       * <code>int32 type = 4;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 留待群聊已读功能，用以区分单聊群聊
       * </pre>
       *
       * <code>int32 type = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:im.MsgRead)
    }

    // @@protoc_insertion_point(class_scope:im.MsgRead)
    private static final com.bx.im.proto.MsgReadProto.MsgRead DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bx.im.proto.MsgReadProto.MsgRead();
    }

    public static com.bx.im.proto.MsgReadProto.MsgRead getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgRead>
        PARSER = new com.google.protobuf.AbstractParser<MsgRead>() {
      @java.lang.Override
      public MsgRead parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgRead(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgRead> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgRead> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bx.im.proto.MsgReadProto.MsgRead getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_MsgRead_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_MsgRead_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022MsgReadProto.proto\022\002im\"B\n\007MsgRead\022\013\n\003u" +
      "id\030\001 \001(\003\022\014\n\004toId\030\002 \001(\003\022\016\n\006msgIds\030\003 \003(\t\022\014" +
      "\n\004type\030\004 \001(\005B\021\n\017com.bx.im.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_im_MsgRead_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_MsgRead_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_MsgRead_descriptor,
        new java.lang.String[] { "Uid", "ToId", "MsgIds", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
