// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgAckProto.proto

package com.bx.im.proto;

public final class MsgAckProto {
  private MsgAckProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgAckOrBuilder extends
      // @@protoc_insertion_point(interface_extends:im.MsgAck)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 消息发起者
     * </pre>
     *
     * <code>int64 senderUid = 1;</code>
     * @return The senderUid.
     */
    long getSenderUid();

    /**
     * <pre>
     * 发给谁
     * </pre>
     *
     * <code>int64 toId = 2;</code>
     * @return The toId.
     */
    long getToId();

    /**
     * <code>string msgId = 3;</code>
     * @return The msgId.
     */
    java.lang.String getMsgId();
    /**
     * <code>string msgId = 3;</code>
     * @return The bytes for msgId.
     */
    com.google.protobuf.ByteString
        getMsgIdBytes();
  }
  /**
   * <pre>
   *消息发送者发出的消息服务器接收后通知其信息已收到
   * </pre>
   *
   * Protobuf type {@code im.MsgAck}
   */
  public static final class MsgAck extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:im.MsgAck)
      MsgAckOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgAck.newBuilder() to construct.
    private MsgAck(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgAck() {
      msgId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MsgAck();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgAck(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              senderUid_ = input.readInt64();
              break;
            }
            case 16: {

              toId_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              msgId_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bx.im.proto.MsgAckProto.internal_static_im_MsgAck_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bx.im.proto.MsgAckProto.internal_static_im_MsgAck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bx.im.proto.MsgAckProto.MsgAck.class, com.bx.im.proto.MsgAckProto.MsgAck.Builder.class);
    }

    public static final int SENDERUID_FIELD_NUMBER = 1;
    private long senderUid_;
    /**
     * <pre>
     * 消息发起者
     * </pre>
     *
     * <code>int64 senderUid = 1;</code>
     * @return The senderUid.
     */
    @java.lang.Override
    public long getSenderUid() {
      return senderUid_;
    }

    public static final int TOID_FIELD_NUMBER = 2;
    private long toId_;
    /**
     * <pre>
     * 发给谁
     * </pre>
     *
     * <code>int64 toId = 2;</code>
     * @return The toId.
     */
    @java.lang.Override
    public long getToId() {
      return toId_;
    }

    public static final int MSGID_FIELD_NUMBER = 3;
    private volatile java.lang.Object msgId_;
    /**
     * <code>string msgId = 3;</code>
     * @return The msgId.
     */
    @java.lang.Override
    public java.lang.String getMsgId() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgId_ = s;
        return s;
      }
    }
    /**
     * <code>string msgId = 3;</code>
     * @return The bytes for msgId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (senderUid_ != 0L) {
        output.writeInt64(1, senderUid_);
      }
      if (toId_ != 0L) {
        output.writeInt64(2, toId_);
      }
      if (!getMsgIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, msgId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (senderUid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, senderUid_);
      }
      if (toId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, toId_);
      }
      if (!getMsgIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, msgId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bx.im.proto.MsgAckProto.MsgAck)) {
        return super.equals(obj);
      }
      com.bx.im.proto.MsgAckProto.MsgAck other = (com.bx.im.proto.MsgAckProto.MsgAck) obj;

      if (getSenderUid()
          != other.getSenderUid()) return false;
      if (getToId()
          != other.getToId()) return false;
      if (!getMsgId()
          .equals(other.getMsgId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SENDERUID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSenderUid());
      hash = (37 * hash) + TOID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getToId());
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + getMsgId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bx.im.proto.MsgAckProto.MsgAck parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bx.im.proto.MsgAckProto.MsgAck parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bx.im.proto.MsgAckProto.MsgAck parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bx.im.proto.MsgAckProto.MsgAck parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bx.im.proto.MsgAckProto.MsgAck parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bx.im.proto.MsgAckProto.MsgAck parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bx.im.proto.MsgAckProto.MsgAck parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bx.im.proto.MsgAckProto.MsgAck parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bx.im.proto.MsgAckProto.MsgAck parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bx.im.proto.MsgAckProto.MsgAck parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bx.im.proto.MsgAckProto.MsgAck parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bx.im.proto.MsgAckProto.MsgAck parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bx.im.proto.MsgAckProto.MsgAck prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *消息发送者发出的消息服务器接收后通知其信息已收到
     * </pre>
     *
     * Protobuf type {@code im.MsgAck}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:im.MsgAck)
        com.bx.im.proto.MsgAckProto.MsgAckOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bx.im.proto.MsgAckProto.internal_static_im_MsgAck_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bx.im.proto.MsgAckProto.internal_static_im_MsgAck_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bx.im.proto.MsgAckProto.MsgAck.class, com.bx.im.proto.MsgAckProto.MsgAck.Builder.class);
      }

      // Construct using com.bx.im.proto.MsgAckProto.MsgAck.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        senderUid_ = 0L;

        toId_ = 0L;

        msgId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bx.im.proto.MsgAckProto.internal_static_im_MsgAck_descriptor;
      }

      @java.lang.Override
      public com.bx.im.proto.MsgAckProto.MsgAck getDefaultInstanceForType() {
        return com.bx.im.proto.MsgAckProto.MsgAck.getDefaultInstance();
      }

      @java.lang.Override
      public com.bx.im.proto.MsgAckProto.MsgAck build() {
        com.bx.im.proto.MsgAckProto.MsgAck result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bx.im.proto.MsgAckProto.MsgAck buildPartial() {
        com.bx.im.proto.MsgAckProto.MsgAck result = new com.bx.im.proto.MsgAckProto.MsgAck(this);
        result.senderUid_ = senderUid_;
        result.toId_ = toId_;
        result.msgId_ = msgId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bx.im.proto.MsgAckProto.MsgAck) {
          return mergeFrom((com.bx.im.proto.MsgAckProto.MsgAck)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bx.im.proto.MsgAckProto.MsgAck other) {
        if (other == com.bx.im.proto.MsgAckProto.MsgAck.getDefaultInstance()) return this;
        if (other.getSenderUid() != 0L) {
          setSenderUid(other.getSenderUid());
        }
        if (other.getToId() != 0L) {
          setToId(other.getToId());
        }
        if (!other.getMsgId().isEmpty()) {
          msgId_ = other.msgId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bx.im.proto.MsgAckProto.MsgAck parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bx.im.proto.MsgAckProto.MsgAck) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long senderUid_ ;
      /**
       * <pre>
       * 消息发起者
       * </pre>
       *
       * <code>int64 senderUid = 1;</code>
       * @return The senderUid.
       */
      @java.lang.Override
      public long getSenderUid() {
        return senderUid_;
      }
      /**
       * <pre>
       * 消息发起者
       * </pre>
       *
       * <code>int64 senderUid = 1;</code>
       * @param value The senderUid to set.
       * @return This builder for chaining.
       */
      public Builder setSenderUid(long value) {
        
        senderUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息发起者
       * </pre>
       *
       * <code>int64 senderUid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderUid() {
        
        senderUid_ = 0L;
        onChanged();
        return this;
      }

      private long toId_ ;
      /**
       * <pre>
       * 发给谁
       * </pre>
       *
       * <code>int64 toId = 2;</code>
       * @return The toId.
       */
      @java.lang.Override
      public long getToId() {
        return toId_;
      }
      /**
       * <pre>
       * 发给谁
       * </pre>
       *
       * <code>int64 toId = 2;</code>
       * @param value The toId to set.
       * @return This builder for chaining.
       */
      public Builder setToId(long value) {
        
        toId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发给谁
       * </pre>
       *
       * <code>int64 toId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearToId() {
        
        toId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object msgId_ = "";
      /**
       * <code>string msgId = 3;</code>
       * @return The msgId.
       */
      public java.lang.String getMsgId() {
        java.lang.Object ref = msgId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msgId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msgId = 3;</code>
       * @return The bytes for msgId.
       */
      public com.google.protobuf.ByteString
          getMsgIdBytes() {
        java.lang.Object ref = msgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msgId = 3;</code>
       * @param value The msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msgId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgId() {
        
        msgId_ = getDefaultInstance().getMsgId();
        onChanged();
        return this;
      }
      /**
       * <code>string msgId = 3;</code>
       * @param value The bytes for msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:im.MsgAck)
    }

    // @@protoc_insertion_point(class_scope:im.MsgAck)
    private static final com.bx.im.proto.MsgAckProto.MsgAck DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bx.im.proto.MsgAckProto.MsgAck();
    }

    public static com.bx.im.proto.MsgAckProto.MsgAck getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgAck>
        PARSER = new com.google.protobuf.AbstractParser<MsgAck>() {
      @java.lang.Override
      public MsgAck parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgAck(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgAck> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgAck> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bx.im.proto.MsgAckProto.MsgAck getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_MsgAck_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_MsgAck_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021MsgAckProto.proto\022\002im\"8\n\006MsgAck\022\021\n\tsen" +
      "derUid\030\001 \001(\003\022\014\n\004toId\030\002 \001(\003\022\r\n\005msgId\030\003 \001(" +
      "\tB\021\n\017com.bx.im.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_im_MsgAck_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_MsgAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_MsgAck_descriptor,
        new java.lang.String[] { "SenderUid", "ToId", "MsgId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
